---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Include {{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"