---
- name: Update apt cache
  ansible.builtin.package:
    update_cache: true

- name: Get jenkins repository key
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add jenkins repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

# TODO: Catch exception and increase timeout https://unix.stackexchange.com/questions/227017/how-to-change-systemd-service-timeout-value
- name: Install jenkins
  ansible.builtin.package:
    update_cache: true
    name: "jenkins"
    state: present
  retries: 30
  delay: 10

- name: Start jenkins.service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: true

- name: Enable firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled

- name: Open 8080
  community.general.ufw:
    rule: allow
    port: "8080"
