---
- name: Get jenkins repository key
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add jenkins repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

- name: Try to get package cache valid time by OS
  ansible.builtin.set_fact:
    cache_time: 1209600

- name: Install jenkins
  ansible.builtin.package:
    update_cache: true
    name: "jenkins"
    state: present
  retries: 30
  delay: 10

- name: Start jenkins.service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: true

- name: Enable firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled

- name: Open 8080
  community.general.ufw:
    rule: allow
    port: "8080"
