---
- name: Try to get package cache valid time by OS
  ansible.builtin.set_fact:
    cache_time: 1209600

- name: Install packages
  ansible.builtin.package:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ main_packages }}"
    - "{{ additional_packages }}"
  retries: 30
  delay: 10