apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
           192.168.49.1 host.minikube.internal
           fallthrough
        }
        forward . 8.8.8.8 {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    log\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    proxy . 8.8.8.8 8.8.4.4\n    hosts {\n       192.168.49.1 host.minikube.internal\n       fallthrough\n    }\n    forward . 8.8.8.8 {\n       max_concurrent 1000\n    }\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-02-23T18:32:00Z","name":"coredns","namespace":"kube-system","resourceVersion":"13305","uid":"32ac1159-9a71-4be5-ade7-46bf5747853f"}}
  creationTimestamp: "2024-02-23T18:32:00Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "13568"
  uid: 32ac1159-9a71-4be5-ade7-46bf5747853f
